apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: emqx
  name: emqx
  namespace: buildingos-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emqx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: emqx
    spec:
      containers:
        - env:
            - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
              value: emqx_prod_2024
            - name: EMQX_DASHBOARD__DEFAULT_USERNAME
              value: admin
            - name: EMQX_HOST
              value: buildingos-emqx-prod
            - name: EMQX_NAME
              value: buildingos-emqx-prod
            - name: EMQX_NODE__COOKIE
              value: emqxsecretcookie_prod
          image: swr.cn-east-3.myhuaweicloud.com/geeqee/emqx:5.8.0
          livenessProbe:
            exec:
              command:
                - /opt/emqx/bin/emqx
                - ctl
                - status
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: buildingos-emqx-prod
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8883
              protocol: TCP
            - containerPort: 18083
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "1073741824"
            requests:
              cpu: 250m
              memory: "536870912"
          volumeMounts:
            - mountPath: /opt/emqx/data
              name: buildingos-prod-emqx-data
            - mountPath: /opt/emqx/log
              name: buildingos-prod-emqx-log
      restartPolicy: Always
      volumes:
        - name: buildingos-prod-emqx-data
          persistentVolumeClaim:
            claimName: buildingos-prod-emqx-data
        - name: buildingos-prod-emqx-log
          persistentVolumeClaim:
            claimName: buildingos-prod-emqx-log
