apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: grafana
  name: grafana
  namespace: buildingos-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_INSTALL_PLUGINS
              value: tdengine-datasource
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: grafana_prod_2024
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SERVER_ROOT_URL
              value: http://localhost:3000
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          image: swr.cn-east-3.myhuaweicloud.com/geeqee/grafana:11.2.0
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:3000/api/health || exit 1
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: buildingos-grafana-prod
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 250m
              memory: "268435456"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: buildingos-prod-grafana-data
            - mountPath: /var/log/grafana
              name: buildingos-prod-grafana-logs
      restartPolicy: Always
      volumes:
        - name: buildingos-prod-grafana-data
          persistentVolumeClaim:
            claimName: buildingos-prod-grafana-data
        - name: buildingos-prod-grafana-logs
          persistentVolumeClaim:
            claimName: buildingos-prod-grafana-logs
