apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: nodered
  name: nodered
  namespace: buildingos-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: nodered
    spec:
      containers:
        - image: swr.cn-east-3.myhuaweicloud.com/geeqee/node-red:prebuilt
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:1880/
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: buildingos-nodered-prod
          ports:
            - containerPort: 1880
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: buildingos-prod-nodered-data
      restartPolicy: Always
      volumes:
        - name: buildingos-prod-nodered-data
          persistentVolumeClaim:
            claimName: buildingos-prod-nodered-data
