apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: tdengine
  name: tdengine
  namespace: buildingos-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tdengine
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: tdengine
    spec:
      containers:
        - env:
            - name: TAOS_FIRST_EP
              value: buildingos-tdengine-prod
            - name: TAOS_FQDN
              value: buildingos-tdengine-prod
            - name: TAOS_HTTP_PORT
              value: "6041"
            - name: TAOS_SERVER_PORT
              value: "6030"
          image: swr.cn-east-3.myhuaweicloud.com/geeqee/tdengine:3.3.2.0
          livenessProbe:
            exec:
              command:
                - taos -s 'show databases;' || exit 1
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: buildingos-tdengine-prod
          ports:
            - containerPort: 6030
              protocol: TCP
            - containerPort: 6041
              protocol: TCP
            - containerPort: 6043
              protocol: TCP
            - containerPort: 6044
              protocol: TCP
            - containerPort: 6060
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "2147483648"
            requests:
              cpu: 500m
              memory: "1073741824"
          volumeMounts:
            - mountPath: /var/lib/taos
              name: buildingos-prod-tdengine-data
            - mountPath: /var/log/taos
              name: buildingos-prod-tdengine-log
      restartPolicy: Always
      volumes:
        - name: buildingos-prod-tdengine-data
          persistentVolumeClaim:
            claimName: buildingos-prod-tdengine-data
        - name: buildingos-prod-tdengine-log
          persistentVolumeClaim:
            claimName: buildingos-prod-tdengine-log
