apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: tdengine
  name: tdengine
  namespace: buildingos-prod
spec:
  ports:
    - name: "6030"
      port: 6030
      targetPort: 6030
    - name: "6041"
      port: 6041
      targetPort: 6041
    - name: "6043"
      port: 6043
      targetPort: 6043
    - name: "6044"
      port: 6044
      targetPort: 6044
    - name: "6060"
      port: 6060
      targetPort: 6060
  selector:
    io.kompose.service: tdengine
