apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: web
  name: web
  namespace: buildingos-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: web
    spec:
      imagePullSecrets:
        - name: swr-cred
      containers:
        - image: swr.cn-east-3.myhuaweicloud.com/geeqee/buildingos-web:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:80/health
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
          name: buildingos-web-prod
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "268435456"
            requests:
              cpu: 250m
              memory: "134217728"
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - mountPath: /var/log/nginx
              name: web-logs-prod
            - mountPath: /mnt/frontend/webroot
              name: buildingos-prod-frontend-data
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: nginx-conf
          configMap:
            name: web-nginx-conf
        - name: web-logs-prod
          persistentVolumeClaim:
            claimName: web-logs-prod
        - name: buildingos-prod-frontend-data
          persistentVolumeClaim:
            claimName: buildingos-prod-frontend-data
            readOnly: true
