apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: zlmediakit
  name: zlmediakit
  namespace: buildingos-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zlmediakit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: zlmediakit
    spec:
      containers:
        - image: swr.cn-east-3.myhuaweicloud.com/geeqee/zlmediakit:master
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost/index/api/getServerConfig
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: buildingos-zlmediakit-prod
          ports:
            - containerPort: 1935
              protocol: TCP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 554
              protocol: TCP
            - containerPort: 10000
              protocol: TCP
            - containerPort: 8000
              protocol: UDP
            - containerPort: 9000
              protocol: UDP
          resources:
            limits:
              cpu: "1"
              memory: "1073741824"
            requests:
              cpu: 500m
              memory: "536870912"
          volumeMounts:
            - mountPath: /opt/media
              name: buildingos-prod-zlmediakit-data
      restartPolicy: Always
      volumes:
        - name: buildingos-prod-zlmediakit-data
          persistentVolumeClaim:
            claimName: buildingos-prod-zlmediakit-data
