apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe -f docker/docker-compose.production.yml convert --namespace buildingos-prod --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: zlmediakit
  name: zlmediakit
  namespace: buildingos-prod
spec:
  ports:
    - name: "1935"
      port: 1935
      targetPort: 1935
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
    - name: "8554"
      port: 8554
      targetPort: 554
    - name: "10000"
      port: 10000
      targetPort: 10000
    - name: "8000"
      port: 8000
      protocol: UDP
      targetPort: 8000
    - name: "9000"
      port: 9000
      protocol: UDP
      targetPort: 9000
  selector:
    io.kompose.service: zlmediakit
